name: UTNetwork-Lobby
version: '${project.version}'
main: tk.utnetwork.utnetworklobby.UTNetworkLobby
authors: [ Ul1ra, Tomsoz ]
description: The core UTNetwork plugin for the lobby.
commands:
  serverselector:
    description: Command that opens a GUI with available game modes.
  profile:
    description: Command that opens a GUI with profile settings.
  rename:
    aliases:
      - irename
    description: Command that renames the held item of a player.